name: Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'src/package-lock.json'

    - name: Install dependencies
      run: |
        cd src
        npm install

    - name: Code Security Scan
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/owasp-top-ten
        continue-on-error: true

    - name: Container Security Scan
      run: |
        # Install Trivy
        sudo apt-get update
        sudo apt-get install wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy
        
        # Scan Dockerfile
        if [ -f "src/Dockerfile" ]; then
          echo "Scanning Dockerfile..."
          trivy config src/Dockerfile
        else
          echo "No Dockerfile found in src/"
        fi
      continue-on-error: true

    - name: Dependency Security Scan
      run: |
        cd src
        echo "Running npm audit..."
        npm audit --audit-level=moderate || true
        
        echo "Running Snyk scan..."
        # Install Snyk
        npm install -g snyk
        snyk test --severity-threshold=high || true
      continue-on-error: true

    - name: Infrastructure Security Scan
      run: |
        # Install tfsec
        wget -O tfsec https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-linux-amd64
        chmod +x tfsec
        sudo mv tfsec /usr/local/bin/
        
        # Install Checkov
        pip install checkov
        
        # Install Terrascan
        wget -O terrascan.tar.gz https://github.com/tenable/terrascan/releases/latest/download/terrascan_1.18.0_Linux_x86_64.tar.gz
        tar -xzf terrascan.tar.gz
        chmod +x terrascan
        sudo mv terrascan /usr/local/bin/
        
        # Scan Terraform files
        if [ -d "terraform" ]; then
          echo "Running tfsec scan..."
          tfsec terraform/ || true
          
          echo "Running Checkov scan..."
          checkov -d terraform/ --output cli || true
          
          echo "Running Terrascan scan..."
          terrascan scan -d terraform/ -o cli || true
        else
          echo "No terraform directory found"
        fi
      continue-on-error: true

    - name: Compliance Check
      run: |
        # Install Conftest
        wget -O conftest https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_linux_amd64.tar.gz
        tar -xzf conftest
        chmod +x conftest
        sudo mv conftest /usr/local/bin/
        
        # Run Conftest
        if [ -d "terraform" ] && [ -d "policies" ]; then
          echo "Running Conftest scan..."
          conftest test terraform/ --policy policies/ --output cli || true
        else
          echo "No terraform or policies directory found"
        fi
      continue-on-error: true

    - name: Security Summary
      if: always()
      run: |
        echo "## Security Scan Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### ✅ Security Scans Completed" >> $GITHUB_STEP_SUMMARY
        echo "- **Code Security:** Semgrep scan completed" >> $GITHUB_STEP_SUMMARY
        echo "- **Container Security:** Trivy scan completed" >> $GITHUB_STEP_SUMMARY
        echo "- **Dependency Security:** npm audit + Snyk scan completed" >> $GITHUB_STEP_SUMMARY
        echo "- **Infrastructure Security:** tfsec + Checkov + Terrascan scan completed" >> $GITHUB_STEP_SUMMARY
        echo "- **Compliance Check:** Conftest scan completed" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📊 Results" >> $GITHUB_STEP_SUMMARY
        echo "All security scans have been executed. Check the logs above for detailed results." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🔧 Next Steps" >> $GITHUB_STEP_SUMMARY
        echo "1. Review any security findings in the logs above" >> $GITHUB_STEP_SUMMARY
        echo "2. Address critical and high severity issues" >> $GITHUB_STEP_SUMMARY
        echo "3. Update security policies as needed" >> $GITHUB_STEP_SUMMARY